version: "3.8"
services:
  postgres:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev-postgres-db
    restart: always
    networks:
      - backend
networks:
  backend:
